# Generated by Django 5.1.7 on 2025-03-28 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_item_add_ons"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="item_name_at_purchase",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="item_price_at_purchase",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="InvoiceItemAddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "addon_name_at_purchase",
                    models.CharField(blank=True, max_length=200),
                ),
                ("addon_price_at_purchase", models.PositiveIntegerField(default=0)),
                (
                    "add_on",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.addon",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.invoiceitem",
                    ),
                ),
            ],
        ),
    ]
