# Generated by Django 5.2 on 2025-04-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_invoiceitem_item_name_at_purchase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="invoices.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitemaddon",
            name="invoice_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_addons",
                to="invoices.invoiceitem",
            ),
        ),
    ]
