# Generated by Django 5.1.7 on 2025-03-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="add_ons",
            field=models.ManyToManyField(related_name="items", to="inventory.addon"),
        ),
    ]
